spring.application.name=sb-redis-cache-eg1





spring.datasource.url=jdbc:postgresql://localhost:9991/mainschema
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.default_schema=tempschema // we will set in the entity class itself






spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data-redis.password=yourpassword (if set) 
#  the username remains "default," and setting spring.data-redis.username is unnecessary unless explicitly configured otherwise
spring.data.redis.username=myuser
spring.data.redis.password=mypassword