spring.application.name=redis-crud-sb3

spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data-redis.password=yourpassword (if set) 
#  the username remains "default," and setting spring.data-redis.username is unnecessary unless explicitly configured otherwise
spring.data.redis.username=myuser
spring.data.redis.password=mypassword